version: "3"

services:
  namenode:
    image: mdt/hadoop-namenode:${HADOOP_TAG}
    hostname: namenode
    container_name: namenode
    volumes:
      - C:\D\volumes\hadoop-net\data\namenode:/hadoop/dfs/name
      - C:\D\volumes\hadoop-net\share:/share
      # - ./data/namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop-hive.env
    ports:
      - "9870:9870"
    networks:
      - hadoop-net
  datanode:
    image: mdt/hadoop-datanode:${HADOOP_TAG}
    hostname: datanode
    container_name: datanode
    volumes:
      - C:\D\volumes\hadoop-net\data\datanode:/hadoop/dfs/data
      - C:\D\volumes\hadoop-net\share:/share
      #- ./data/datanode:/hadoop/dfs/data

    env_file:
      - ./hadoop-hive.env
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    ports:
      - "9864:9864"
    depends_on:
      - namenode
    healthcheck:
      interval: 10s
      retries: 100 
    networks:
      - hadoop-net
  resourcemanager:
    image: mdt/hadoop-resourcemanager:${HADOOP_TAG}
    hostname: resourcemanager
    container_name: resourcemanager
    environment:
      SERVICE_PRECONDITION: "namenode:9870 datanode:9864"
    volumes:
      - C:\D\volumes\hadoop-net\share:/share
    ports:
      - 8088:8088
    env_file:
      - ./hadoop-hive.env
    depends_on:
      - namenode
      - datanode
    healthcheck:
      interval: 10s
      retries: 100 
    networks:
      - hadoop-net
  historyserver:
    image: mdt/hadoop-historyserver:${HADOOP_TAG}
    hostname: historyserver
    container_name: historyserver
    environment:
      SERVICE_PRECONDITION: "namenode:9870 datanode:9864 resourcemanager:8088"
    volumes:
      
      - C:\D\volumes\hadoop-net\hadoop_historyserver:/hadoop/yarn/timeline
      - C:\D\volumes\hadoop-net\share:/share
      #- ./data/hadoop_historyserver:/hadoop/yarn/timeline
    env_file:
      - ./hadoop-hive.env
    depends_on:
      - resourcemanager
    healthcheck:
      interval: 10s
      retries: 100 
    networks:
      - hadoop-net
  hive-server:
    image: mdt/hive:${HIVE_TAG}
    hostname: hive-server
    container_name: hive-server
    env_file:
      - ./hadoop-hive.env
    # command: /opt/hive/bin/hive --service hiveserver2
    environment:
      SERVICE_PRECONDITION: "hive-metastore:9083"
      HIVE_CORE_CONF_javax_jdo_option_ConnectionURL: "jdbc:postgresql://hive-metastore/metastore"
    volumes:
      - C:\D\volumes\hadoop-net\share:/share
    ports:
      - "10000:10000"
    depends_on:
      - hive-metastore
    healthcheck:
      interval: 10s
      retries: 100 
    networks:
      - hadoop-net
  hive-metastore:
    image: mdt/hive:${HIVE_TAG}
    hostname: hive-metastore
    container_name: hive-metastore
    env_file:
      - ./hadoop-hive.env
    command: /opt/hive/bin/hive --service metastore
    environment:
      SERVICE_PRECONDITION: "namenode:9870 datanode:9864 hive-metastore-postgresql:5432"
    volumes:
      - C:\D\volumes\hadoop-net\share:/share
    ports:
      - "9083:9083"
    depends_on:
      - historyserver
    healthcheck:
      interval: 10s
      retries: 100 
    networks:
      - hadoop-net
  ldap:
    hostname: ldap
    container_name: ldap
    image: osixia/openldap:1.2.4
    volumes:
      - C:\D\volumes\hadoop-net\share:/share
    ports:
      - 389:389
      - 636:636
    depends_on:
      - namenode
      - datanode
      - hive-server
    healthcheck:
      interval: 10s
      retries: 100 
    networks:
      - hadoop-net  
  ldapweb:
    image: osixia/phpldapadmin:0.7.2
    container_name: ldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: ldap
    volumes:
      - C:\D\volumes\hadoop-net\share:/share
    ports:
      - 6443:443
    depends_on:
      - namenode
      - ldap
    healthcheck:
      interval: 10s
      retries: 100 
    networks:
      - hadoop-net
  hue:
    image: mdt/hue:${HUE_TAG}
    hostname: hue
    container_name: hue
    environment:
      - NAMENODE_HOST=namenode
    env_file:
      - ./hadoop-hive.env
    ports:
     - "8888:8888"
    volumes:
      - ./pseudo-distributed.ini:/usr/share/hue/desktop/conf/pseudo-distributed.ini
      - C:\D\volumes\hadoop-net\share:/share
      # - ./pseudo-distributed.ini:/usr/share/hue/desktop/conf/z-hue.ini
    depends_on:
      - hive-server
    healthcheck:
      interval: 10s
      retries: 100 
    networks:
      - hadoop-net 
 
volumes:
  data:

networks:
  hadoop-net:
    external:
      name: hadoop-net
