version: "3"

services:
  namenode:
    image: mdt/hadoop-namenode:${HADOOP_TAG}
    hostname: namenode
    container_name: namenode
    volumes:
      - C:\D\volumes\hadoop-net\data\namenode:/hadoop/dfs/name
      - C:\D\volumes\hadoop-net\share:/share
      # - ./data/namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop-hive.env
    ports:
      - "9870:9870"
    networks:
      - hadoop-net
  datanode:
    image: mdt/hadoop-datanode:${HADOOP_TAG}
    hostname: datanode
    container_name: datanode
    volumes:
      - C:\D\volumes\hadoop-net\data\datanode:/hadoop/dfs/data
      - C:\D\volumes\hadoop-net\share:/share
      #- ./data/datanode:/hadoop/dfs/data

    env_file:
      - ./hadoop-hive.env
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    ports:
      - "9864:9864"
      - "8042:8042"
    depends_on:
      - namenode
    healthcheck:
      interval: 10s
      retries: 100 
    networks:
      - hadoop-net
 
  datanode2:
    image: mdt/hadoop-datanode:${HADOOP_TAG}
    hostname: datanode2
    container_name: datanode2
    volumes:
      - C:\D\volumes\hadoop-net\data\datanode2:/hadoop/dfs/data
      - C:\D\volumes\hadoop-net\share:/share
      #- ./data/datanode:/hadoop/dfs/data

    env_file:
      - ./hadoop-hive.env
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    ports:
      - "9865:9864"
      - "8043:8042"
    depends_on:
      - namenode
    healthcheck:
      interval: 10s
      retries: 100 
    networks:
      - hadoop-net

  datanode3:
    image: mdt/hadoop-datanode:${HADOOP_TAG}
    hostname: datanode3
    container_name: datanode3
    volumes:
      - C:\D\volumes\hadoop-net\data\datanode3:/hadoop/dfs/data
      - C:\D\volumes\hadoop-net\share:/share
      #- ./data/datanode:/hadoop/dfs/data

    env_file:
      - ./hadoop-hive.env
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    ports:
      - "9866:9864"
      - "8044:8042"
    depends_on:
      - namenode
    healthcheck:
      interval: 10s
      retries: 100 
    networks:
      - hadoop-net
 



volumes:
  data:

networks:
  hadoop-net:
    external:
      name: hadoop-net
