version: '2'
services:

  ldap-admin:
    image: osixia/phpldapadmin:latest
    container_name: ldapadmin
    ports:
      - "6080:80"
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=ldap
      - PHPLDAPADMIN_HTTPS=false
    networks:
      mynet:

networks:
  mynet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.31.0.0/16
          gateway: 172.31.0.1
 