version: '2'
services:

  # ldap:
  #   image: osixia/openldap:1.2.5
  #   container_name: ldap
  #   command: --loglevel debug
  #   volumes:
  #       - C:\D\volumes\ldap\share:/share
  #       - C:\D\volumes\ldap\database:/var/lib/ldap
  #       - C:\D\volumes\ldap\slapd\config:/etc/ldap/slapd.d
  #       - C:\D\volumes\ldap\private:/container/service/slapd/assets/certs
  #   environment:
  #     LDAP_LOG_LEVEL: "256"
  #     LDAP_ORGANISATION: "Example Inc."
  #     LDAP_DOMAIN: "example.org"
  #     LDAP_BASE_DN: "dc=example,dc=org"
  #     LDAP_ADMIN_PASSWORD: "admin"
  #     LDAP_CONFIG_PASSWORD: "config"
  #     LDAP_READONLY_USER: "true"
  #     LDAP_READONLY_USER_USERNAME: "readonly"
  #     LDAP_READONLY_USER_PASSWORD: "readonly"
  #     LDAP_RFC2307BIS_SCHEMA: "true"
  #     LDAP_BACKEND: "mdb"
  #     LDAP_TLS: "false"
  #     LDAP_TLS_CRT_FILENAME: "ldap.crt"
  #     LDAP_TLS_KEY_FILENAME: "ldap.key"
  #     LDAP_TLS_CA_CRT_FILENAME: "ca.crt"
  #     LDAP_TLS_ENFORCE: "true"
  #     LDAP_TLS_CIPHER_SUITE: "SECURE256:-VERS-SSL3.0"
  #     LDAP_TLS_PROTOCOL_MIN: "3.1"
  #     LDAP_TLS_VERIFY_CLIENT: "demand"
  #     LDAP_REPLICATION: "true"
  #     LDAP_REPLICATION_CONFIG_SYNCPROV: "binddn=\"cn=admin,cn=config\" bindmethod=simple credentials=$${LDAP_CONFIG_PASSWORD} searchbase=\"cn=config\" type=refreshAndPersist retrue=\"60 +\" timeout=1 starttls=critical"
  #     LDAP_REPLICATION_DB_SYNCPROV: "binddn=\"cn=admin,$${LDAP_BASE_DN}\" bindmethod=simple credentials=$${LDAP_ADMIN_PASSWORD} searchbase=\"$${LDAP_BASE_DN}\" type=refreshAndPersist interval=00:00:00:10 retrue=\"60 +\" timeout=1 starttls=critical"
  #     LDAP_REPLICATION_HOSTS: "#PYTHON2BASH:['ldap://ds1.dom.com', 'ldap://ds2.dom.com']"
  #     KEEP_EXISTING_CONFIG: "true"
  #     LDAP_REMOVE_CONFIG_AFTER_SETUP: "true"
  #     LDAP_SSL_HELPER_PREFIX: "ldap"
  #   tty: true
  #   stdin_open: true
  #   ports:
  #     - 389:389
  #     - 636:636
  #   networks:
  #     mynet:

  ldap-admin:
    image: osixia/phpldapadmin:latest
    container_name: ldapadmin
    command: --loglevel debug
    ports:
      - "6080:80"
  #   volumes:
  #     - C:\D\volumes\ldap\private\ldap-client.crt:/container/service/ldap-client/assets/certs/ldap-client.crt
  #     - C:\D\volumes\ldap\private\ldap-client.key:/container/service/ldap-client/assets/certs/ldap-client.key
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=ldap
      - PHPLDAPADMIN_HTTPS=false
    networks:
      mynet:

networks:
  mynet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.31.0.0/16
          gateway: 172.31.0.1
 